language: python
python:
  - "3.6"
# command to install dependencies
install: pip install -r requirements.txt
before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'create database yummys_db;' -U postgres
# command to run tests.py
script: python -m pytest --cov=app
after_success:
  - coveralls