"""empty message

Revision ID: 360a3d1cccf4
Revises: 9e3e6acc0d39
Create Date: 2017-12-09 13:34:49.087316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360a3d1cccf4'
down_revision = '9e3e6acc0d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'instructions')
    # ### end Alembic commands ###
